### ISSUE TITLE
Download Link for NTIRE 2022 Image Inpainting Challenge

### ISSUE THREAD

**Issue by fenglinglwb** [affromero/NTIRE22_Inpainting#2]
I am writing regarding the download link provided for the competition data, which unfortunately appears to be no longer accessible.

Test Set + Masks: https://polybox.ethz.ch/index.php/s/qnf3NglUDqmvGBr
Test Ground-Truth: https://polybox.ethz.ch/index.php/s/vwT1xCPIOwbb6t7

I would greatly appreciate it if you could kindly assist me in obtaining the test data. If it is possible, could you please provide an alternative download link or share the data with me directly? 

Thank you very much for your attention to this matter.

**Comment by affromero** [comment]
Hello, 
Sorry for that. 
I don’t have access to my pc right now. I’ll update you with the updated link at the end of this month.

**Comment by fenglinglwb** [comment]
Thanks for your kink help.

**Comment by affromero** [comment]
Hello, I do not have much experience with the HF hub, yet I put it here: https://huggingface.co/datasets/afromero/NTIRE22_Inpainting/tree/main
Let me know if that works/helps.

**Comment by fenglinglwb** [comment]
Thanks for your kind help.
