### ISSUE TITLE
Question about Artificially Inspired method: CoMod GAN or modified U-net?

### ISSUE THREAD

**Issue by z-pan** [affromero/NTIRE22_Inpainting#3]
Hi, I was trying to run inference with Artificially Inspired models, and I found that there are two types of models: 1. A modified U-net model for Every-N-Lines and Nearest Neighbors mask types; 2. CoMod GAN for the other mask types. 

So, does the Artificially Inspired method use two different network architectures (modified U-net and CoMod GAN) for different cases as said above?

Thank you!

**Comment by affromero** [comment]
Hello, 
You are right. [Here](https://github.com/affromero/NTIRE22_Inpainting/blob/main/inference/ArtificiallyInspired/track1/inference/utils.py#L72). Unfortunately, the conditions of the challenge did not prevent this scenario. It is also important to say that this information was never disclosed from the authors in the report of the challenge. 
We are sorry for the inconvenience it might cause.
